### PR TITLE
Raspi pico pio uart

### PR DESCRIPTION
**Pull request by MrGreensWorkshop**

### CODE REVIEW

**Comment by MrGreensWorkshop** [comment]
@yonsch I know it's not best place to ask this question but I don't think anyone other than [Yonatan Schachter](https://github.com/yonsch) can help me. Sorry to bother you like this.

There is [encoder pulse reader sample](https://github.com/adamgreen/QuadratureDecoder) which I'm trying to write a driver for zephyr rtos using pio driver supplied by you. Thank you again.

I tested the [encoder sample](https://github.com/adamgreen/QuadratureDecoder) with pico sdk and it works perfectly.

branch  -> https://github.com/MrGreensWorkshop/zephyr/tree/raspi-pico-quadrature-decoder
temporary sample code  -> /zephyr/samples/sensor/qdec

when I send the pulses, It doesn't count pulses. When I debug the code, driver loads, getting count from DMA but count is not correct. or no count output.

few times I saw log output  enc1.. like this.

```
*** Booting Zephyr OS build zephyr-v3.1.0-1900-g62a60cc4bb83  ***
Quadrature Decoder sample application
enc1 position is -44753
enc1 position is 0
```
Could you advise me any dubug suggestion please? 
Thank you!.

**Comment by yonsch** [comment]
In a quick glance, I think the problem is in your dts. You should create a node for your sensor which is a child of the PIO, then enable it in your overlay. What you did was to modify the label and compatible of the PIO itself.
It might also be your usage of the DMA, but I have no experience with it so I can't help with that.

**Comment by MrGreensWorkshop** [comment]
Thank you for checking out. I really appreciated.

About dts, actually first I did like you described. Result was same.
When this project finished I want to make PR to zephyr os, so I didn't want to left in rp2040.dtsi. I think nodes can be created in this way too.  But I will listen your advice and check again.

I was thinking about maybe problem is related with DMA.

**Comment by MrGreensWorkshop** [comment]
@yonsch Hi, it's me again. Sorry to bother you.

I used this sample this time no DMA and I check on my setup, it's working.
https://github.com/raspberrypi/pico-examples/tree/master/pio/quadrature_encoder

This is the commit 091e423 I made, dts written as you advised. Still no luck.

Is there any chance to take a look? Thank you!

**Comment by MrGreensWorkshop** [comment]
@yonsch I found the problem after debugging line by line. I'm not sure what causing this but it's strange.

nothing changed in 091e423

this is only change that I made

~/zephyrproject/modules/hal/rpi_pico/src/rp2_common/hardware_pio/pio.c

```
// these assert if unable
uint pio_add_program(PIO pio, const pio_program_t *program) {
    uint32_t save = hw_claim_lock();
    int offset = _pio_find_offset_for_program(pio, program);
    if (offset < 0) {
        panic("No program space");
    }
    offset = 0;   // it should be zero. force to zero.
    _pio_add_program_at_offset(pio, program, (uint)offset);
    hw_claim_unlock(save);
    return (uint)offset;
}
```

when adding pio program in this func, return of _pio_find_offset_for_program (offset) was 3? 
it should be 0 right. It didn't seem right and I forced to set to zero. Then everything is works as excepted.
But why? Do you have any idea?

**Comment by MrGreensWorkshop** [comment]
I want  to share what I found so far.

this loads program into wrong offset. I don't have any idea why?
`pio_add_program(pio, &qdec_pio_program);`

so I decide to use 
`pio_add_program_at_offset(pio, &qdec_pio_program, 0);`

btw, example which uses DMA also works fine with this.

about dts, I didn't add to anything into 
/Users/wizard/zephyrproject/zephyr/dts/arm/rpi_pico/rp2040.dtsi 

with this pio_qdec0 will be added into pio0.

app.overlay
```
&pinctrl {
	pio_qdec0_default: pio_qdec0_default {
		group1 {
			pinmux = <PIO0_P14>;
			input-enable;
		};
		group2 {
			pinmux = <PIO0_P15>;
                        input-enable;
		};
	};
};

&pio0 {
 	status = "okay";
        pio_qdec0: qdec {
                compatible = "raspberrypi,pico-qdec-pio";
                label = "QDEC_0";
                pinctrl-0 = <&pio_qdec0_default>;
                pinctrl-names = "default";
    };
};
```

prf.conf
```
CONFIG_SENSOR=y
CONFIG_QDEC_RPI_PICO_PIO=y
```

**Pull request merged**
